/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chapter4;

import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

// Write a program that:
// * Calculates the "FizzBuzz sequence" from 1 to 20.
//   * For each integer between 1 and 20 (inclusive).
//     * If the number is divisible by 3, replace the number with `Fizz`.
//     * If the number is divisible by 5, replace the number with `Buzz`
//     * If the number is divisible by 3 and 5, replace the number with
//       `FizzBuzz`.
//     * If the number is divisible by neither 3 or 5, keep the number.
// * `puts`es these "FizzBuzz sequence" entries, one per line.

public class FizzBuzzTest {
    @Test public void PutsFizzBuzzFor1_20() {
        FizzBuzz FB = new FizzBuzz();
        ArrayList<String> FizzBuzzArrayList = new ArrayList<String>();
        FizzBuzzArrayList.add("1");
        FizzBuzzArrayList.add("2");
        FizzBuzzArrayList.add("Fizz");
        FizzBuzzArrayList.add("4");
        FizzBuzzArrayList.add("Buzz");
        FizzBuzzArrayList.add("Fizz");
        FizzBuzzArrayList.add("7");
        FizzBuzzArrayList.add("8");
        FizzBuzzArrayList.add("Fizz");
        FizzBuzzArrayList.add("Buzz");
        FizzBuzzArrayList.add("11");
        FizzBuzzArrayList.add("Fizz");
        FizzBuzzArrayList.add("13");
        FizzBuzzArrayList.add("14");
        FizzBuzzArrayList.add("FizzBuzz");
        FizzBuzzArrayList.add("16");
        FizzBuzzArrayList.add("17");
        FizzBuzzArrayList.add("Fizz");
        FizzBuzzArrayList.add("19");
        FizzBuzzArrayList.add("Buzz");
        assertEquals(FizzBuzzArrayList, FB.FizzBuzzMethod(20));
    }
}
