/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package change_converter;

import java.util.ArrayList;

public class ChangeConverter {

    public ArrayList<String> Change = new ArrayList<String>();
    public ArrayList<String> GetChange(Double AmountInPounds) {
        Double PennyDouble = AmountInPounds * 100;
        int AmountInPennies = (int) Math.round(PennyDouble);
        //Putting the amounts in pennies is tidier than rounding the decimal places in the long run...

        while (AmountInPennies >= 5000) {
            Change.add("£50");
            AmountInPennies -= 5000;
        } while (AmountInPennies >= 2000) {
            Change.add("£20");
            AmountInPennies -= 2000;
        } while (AmountInPennies >= 1000) {
            Change.add("£10");
            AmountInPennies -= 1000;
        } while (AmountInPennies >= 500) {
            Change.add("£5");
            AmountInPennies -= 500;
        } while (AmountInPennies >= 200) {
            Change.add("£2");
            AmountInPennies -= 200;
        } while (AmountInPennies >= 100) {
            Change.add("£1");
            AmountInPennies -= 100;
        } while (AmountInPennies >= 50) {
            Change.add("50p");
            AmountInPennies -= 50;
        } while (AmountInPennies >= 20) {
            Change.add("20p");
            AmountInPennies -= 20;
        } while (AmountInPennies >= 10) {
            Change.add("10p");
            AmountInPennies -= 10;
        } while (AmountInPennies >= 5) {
            Change.add("5p");
            AmountInPennies -= 5;
        } while (AmountInPennies >= 2) {
            Change.add("2p");
            System.out.println(AmountInPennies);
            AmountInPennies -= 2;
            System.out.println(AmountInPennies);
        } while (AmountInPennies >= 1) {
            Change.add("1p");
            AmountInPennies -= 1;
        }
        return Change;
    }
}
