/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package echo;

import java.util.ArrayList;

public class Echo {
    public String EchoUser(ArrayList<String> TextInput) {
        for (Integer Element = 0; Element < TextInput.size(); Element++) {
            if (ArrayList(Element))
        }
    }
}
