/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package change_converter;

import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class ChangeConverterTest {
    @Test public void GivesChangeFor6_42() {
        ChangeConverter Converter = new ChangeConverter();
        ArrayList<String> Change = new ArrayList<String>();
        Change.add("£5");
        Change.add("£1");
        Change.add("20p");
        Change.add("20p");
        Change.add("2p");
        assertEquals(Change, Converter.GetChange(6.42));
    }

    @Test public void GivesChangeFor40() {
        ChangeConverter Converter = new ChangeConverter();
        ArrayList<String> Change = new ArrayList<String>();
        Change.add("£20");
        Change.add("£20");
        assertEquals(Change, Converter.GetChange(40.00));
    }

    @Test public void GivesChangeFor16_30() {
        ChangeConverter Converter = new ChangeConverter();
        ArrayList<String> Change = new ArrayList<String>();
        Change.add("£10");
        Change.add("£5");
        Change.add("£1");
        Change.add("20p");
        Change.add("10p");
        assertEquals(Change, Converter.GetChange(16.30));
    }

        @Test public void GivesChangeFor19_99() {
            ChangeConverter Converter = new ChangeConverter();
            ArrayList<String> Change = new ArrayList<String>();
            Change.add("£10");
            Change.add("£5");
            Change.add("£2");
            Change.add("£2");
            Change.add("50p");
            Change.add("20p");
            Change.add("20p");
            Change.add("5p");
            Change.add("2p");
            Change.add("2p");
            assertEquals(Change, Converter.GetChange(19.99));
        }

    @Test public void GivesChangeFor76_81() {
        ChangeConverter Converter = new ChangeConverter();
        ArrayList<String> Change = new ArrayList<String>();
        Change.add("£50");
        Change.add("£20");
        Change.add("£5");
        Change.add("£1");
        Change.add("50p");
        Change.add("20p");
        Change.add("10p");
        Change.add("1p");
        assertEquals(Change, Converter.GetChange(76.81));
    }
}
