/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chapter4;

import java.util.ArrayList;

public class FizzBuzz {
    public ArrayList<String> FizzBuzzMethod(Integer last_number) {
        Integer Count = 1;
        ArrayList<String> FizzBuzzArray = new ArrayList<String>();
        while (Count <= last_number) {
            if (Count % 3 == 0 && Count % 5 == 0) {
                FizzBuzzArray.add("FizzBuzz");
                Count += 1;
            } else if (Count % 3 == 0) {
                FizzBuzzArray.add("Fizz");
                Count += 1;
            } else if (Count % 5 == 0) {
                FizzBuzzArray.add("Buzz");
                Count += 1;
            } else {
                String CountString = String.format("%s", Count);
                FizzBuzzArray.add(CountString);
                Count += 1;
            }
        }
        return FizzBuzzArray;
    }
}
