/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package checkout;

public class Checkout {
    public Integer CounterA = 0;
    public Integer CounterB = 0;
    public Integer CounterC = 0;
    public Integer CounterD = 0;

    public Integer getPriceOfAs() {
        if (CounterA % 3 == 0) {
            CounterA = CounterA / 3 * 130;
        } else {
            Integer IndividualA = CounterA % 3;
            CounterA = CounterA / 3 * 130;
            CounterA += IndividualA * 50;
        }
        return CounterA;
    }

    public Integer getPriceOfBs() {
        if (CounterB % 2 == 0) {
            CounterB = CounterB / 2 * 45;
        } else {
            Integer IndividualB = CounterB % 2;
            CounterB = CounterB / 3 * 45;
            CounterB += IndividualB * 30;
        }
        return CounterB;
    }


    public Integer CheckoutPrice = 0;

    public Integer checkout(String Items) {
        String[] ItemsArray = Items.split("");
        Integer ItemsLength = ItemsArray.length;
        for (Integer Index = 0; Index < ItemsLength; Index++) {
            switch (ItemsArray[Index]) {
                case "A":
                    CounterA += 1;
                    break;
                case "B":
                    CounterB += 1;
                    break;
                case "C":
                    CounterC += 1;
                    break;
                case "D":
                    CounterD += 1;
                    break;
                default:
                    return -1;
            }
        }
        CheckoutPrice += getPriceOfAs();
        CheckoutPrice += getPriceOfBs();
        CheckoutPrice += 20 * CounterC;
        CheckoutPrice += 15 * CounterD;
        return CheckoutPrice;
    }
}
