/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;

import java.util.ArrayList;

public class Game {
    String str_guess;

    public Game(String guess) {
        str_guess = guess;
    }

    public static void main(String[] args) {
        Game game = new Game("MAKERS");
        System.out.println(game.getWordToGuess("MITTENS"));
    }

    public ArrayList<String> arr_reveal = new ArrayList<String>();

    public String getWordToGuess(String str_answer) {
        String[] arr_answer = str_answer.split("");
        Integer length_answer = arr_answer.length;
        for (Integer index = 0; index < length_answer; index++) {
            if (str_guess.contains(arr_answer[index])) {
                arr_reveal.add(arr_answer[index]);
            } else {
                arr_reveal.add("-");
            }
        }
        String str_reveal = String.join("", arr_reveal);
        return (str_reveal);
    }
}
