/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package checkout;

import org.junit.Test;
import static org.junit.Assert.assertEquals;

public class CheckoutTest {
    @Test public void String_aBc_IsInvalid() {
        Checkout shop = new Checkout();
        assertEquals("String of aBc returns -1", Integer.valueOf(-1), shop.checkout("aBc"));
    }

    @Test public void String_B8x_IsInvalid() {
        Checkout shop = new Checkout();
        assertEquals("String of -B8x returns -1", Integer.valueOf(-1), shop.checkout("-B8x"));
    }

    @Test public void String_18_IsInvalid() {
        Checkout shop = new Checkout();
        assertEquals("String of 18 returns -1", Integer.valueOf(-1), shop.checkout("18"));
    }

    @Test public void String_AA_Is100() {
        Checkout shop = new Checkout();
        assertEquals("String of AA returns 100", Integer.valueOf(100), shop.checkout("AA"));
    }

    @Test public void String_ABCD_Is100() {
        Checkout shop = new Checkout();
        assertEquals("String of ABCD returns 115", Integer.valueOf(115), shop.checkout("ABCD"));
    }

    @Test public void String_AAA_Is130() {
        Checkout shop = new Checkout();
        assertEquals("String of AAA returns 130", Integer.valueOf(130), shop.checkout("AAA"));
    }

    @Test public void String_AAAABBB_Is255() {
        Checkout shop = new Checkout();
        assertEquals("String of AAAABBB returns 255", Integer.valueOf(255), shop.checkout("AAAABBB"));
    }
}
