/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class GameTest {
    @Test public void testGetsWordToGuess() {
        Game game = new Game("MAKERS");
        assertEquals("M---E-S", game.getWordToGuess("MITTENS"));
    }
}
