/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package middle_letter;

import org.junit.Test;
import static org.junit.Assert.*;

public class MiddleLetterTest {
    @Test public void ReturnsES
}
