/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leap_years;

import java.util.ArrayList;

public class LeapYears {

    public ArrayList<Integer> leap_years = new ArrayList<>();
    public Boolean check_leap(Integer year) {
        if (year % 400 == 0) {
            return true;
        } else if (year % 100 == 0) {
            return false;
        } else if (year % 4 == 0) {
            return true;
        } else {
            return false;
        }
    }

    public ArrayList<Integer> leap_list(Integer start_year, Integer end_year) {
        for (Integer year = start_year; year <= end_year; year++) {
            if (check_leap(year)) {
                leap_years.add(year);
            }
        }
        return leap_years;
    }
}
