/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leap_years;

public class LeapYears {
    public Boolean check_leap(Integer year) {
        if (year % 400 == 0) {
            return true;
        } else if (year % 100 == 0) {
            return false;
        } else if (year % 4 == 0) {
            return true;
        } else {
            return false;
        }
    }
}
