/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ten_minute_walk;

import java.lang.reflect.Array;

public class TenMinuteWalk {
    public Boolean IsItTenMinutes(String[] route) {
        Integer VerticalRoute = 0;
        Integer HorizontalRoute = 0;
        Integer ArrayLength = route.length;
        if (ArrayLength != 10) {
            return false;
        }

        for (Integer index = 0; index < ArrayLength; index++) {
            if (route[index] == "n") {
                VerticalRoute += 1;
            } else if (route[index] == "e") {
                HorizontalRoute += 1;
            } else if (route[index] == "s") {
                VerticalRoute -= 1;
            } else {
                HorizontalRoute -= 1;
            }
        }
        if (VerticalRoute == 0 && HorizontalRoute == 0) {
            return true;
        } else {
            return false;
        }
    }
}
