/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scrabble_solver;

import org.junit.Test;
import static org.junit.Assert.assertEquals;

public class ScrabbleSolverTest {
    @Test public void EmptyStringScores0() {
        ScrabbleSolver solver = new ScrabbleSolver();
        assertEquals("empty string should have a score of 0", Integer.valueOf(0), solver.score(" "));
    }

    @Test public void StringWithSymbolsScores0() {
        ScrabbleSolver solver = new ScrabbleSolver();
        assertEquals("string with symbols should have a score of 0", Integer.valueOf(0), solver.score(" \t\n"));
    }

    @Test public void AScores1() {
        ScrabbleSolver solver = new ScrabbleSolver();
        assertEquals("a should have a score of 1", Integer.valueOf(1), solver.score("a"));
    }

    @Test public void FScores4() {
        ScrabbleSolver solver = new ScrabbleSolver();
        assertEquals("f should have a score of 4", Integer.valueOf(4), solver.score("f"));
    }

    @Test public void StreetScores6() {
        ScrabbleSolver solver = new ScrabbleSolver();
        assertEquals("street should have a score of 6", Integer.valueOf(6), solver.score("street"));
    }

    @Test public void QuirkyScores22() {
        ScrabbleSolver solver = new ScrabbleSolver();
        assertEquals("quirky should have a score of 22", Integer.valueOf(22), solver.score("quirky"));
    }

    @Test public void OXYPHENBUTAZONEScores41() {
        ScrabbleSolver solver = new ScrabbleSolver();
        assertEquals("OXYPHENBUTAZONE should have a score of 41", Integer.valueOf(41), solver.score("OXYPHENBUTAZONE"));
    }
}
